### PR TITLE
General update

### PR DESCRIPTION
**Pull request by aa-hernandez**

### CODE REVIEW

**Review by zhmiao — APPROVED** [review]
Readme Minor updates

**Review by zhmiao — CHANGES_REQUESTED** [review]
Add an announcement: "Microsoft is working on expanding the CameraTraps repo. We will continue to support and maintain Megadetector for the community and more."

**Comment by aa-hernandez** [comment]
Changes have been made!

**Review by zhmiao — APPROVED** [review]
Announcement added. Thanks

**Pull request merged**
