### PR TITLE
Update ocr_sandbox.py

### PR DESCRIPTION
**Pull request by mostafa-sa3ed**

### CODE REVIEW

**Comment by yangsiyu007** [comment]
I don't think `++` works as an increment shorthand...

**Comment by mostafa-sa3ed** [comment]
It does

**Comment by mostafa-sa3ed** [comment]
Ok sorry it is working in c/c++/java/php but not in python

I tried it and found it doesn't work

**Comment by yangsiyu007** [comment]
https://stackoverflow.com/questions/1485841/behaviour-of-increment-and-decrement-operators-in-python

**Comment by mostafa-sa3ed** [comment]
Thanks a lot , i am a student and always open to learn

**Pull request closed without merging**
